# GET https://beer.fluentcloud.com/v1/beer HTTP/1.1
# content-type: application/json

POST https://beer.fluentcloud.com/v1/beer HTTP/1.1
content-type: application/json

{
  "name": "Natural Ice",
  "likes": "5"
}
